# simple-web-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksweb
  template:
    metadata:
      labels:
        app: eksweb
    spec:
      containers:
      - name: eksweb
        image: oxfordfun/eksweb:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: eks-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: eksweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
 