---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app-sa
  namespace: web-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web-apps
  name: web-app-read-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-app-rolebinding
  namespace: web-apps
subjects:
- kind: ServiceAccount
  name: web-app-sa
  namespace: web-apps
roleRef:
  kind: Role
  name: web-app-read-role
  apiGroup: rbac.authorization.k8s.io
